providers:
    azurerm: {}

resources:
  - type: azurerm_resource_group
    name: rsgabc
    properties:
      name: resa
      location: West Europe

  - type: azurerm_virtual_network
    name: rsgabc-vnet
    properties:
      name: azure-network
      location: West Europe
      address_space: ["10.0.0.0/16"]
      resource_group_name: rsgabc

  - type: azurerm_subnet
    name: rsgabc-subnet
    properties:
      name: internal
      resource_group_name: rsgabc
      virtual_network_name: azure-network
      address_prefixes: ["10.0.2.0/24"]

  - type: azurerm_windows_virtual_machine_scale_set
    name: rsgabc-vmss
    properties:
      name: example-vmss
      resource_group_name: rsgabc
      location: West Europe
      sku: Standard_F2
      instances: 2
      admin_password: Devimounika@21
      admin_username: Mounika
      computer_name_prefix: vm-
      source_image_reference:
        publisher: MicrosoftWindowsServer
        offer: WindowsServer
        sku: 2016-Datacenter-Server-Core
        version: latest
      os_disk:
        storage_account_type: Standard_LRS
        caching: ReadWrite
      network_interface:
        - name: ntif
          properties:
            ip_configuration:
              - name: internal
                primary: true
                subnet_id: rsgabc-subnet

  - type: azurerm_monitor_autoscale_setting
    name: rsgabc-autoscale
    properties:
      name: first-autoscale
      resource_group_name: rsgabc
      location: West Europe
      target_resource_id: azurerm_windows_virtual_machine_scale_set.rsgabc-vmss.id
      profiles:
        - name: defaultProfile
          capacity:
            minimum: 1
            maximum: 10
            default: 2
          rules:
            - metric_trigger:
                metric_name: "Percentage CPU"
                metric_resource_id: azurerm_windows_virtual_machine_scale_set.rsgabc-vmss.id
                operator: GreaterThan
                statistic: Average
                threshold: 75
                time_grain: PT1M
                time_window: PT5M
                time_aggregation: Average
              scale_action:
                direction: Increase
                type: ChangeCount
                value: 1
                cooldown: PT5M
            - metric_trigger:
                metric_name: "Percentage CPU"
                metric_resource_id: azurerm_windows_virtual_machine_scale_set.rsgabc-vmss.id
                operator: LessThan
                statistic: Average
                threshold: 25
                time_grain: PT1M
                time_window: PT5M
                time_aggregation: Average
              scale_action:
                direction: Decrease
                type: ChangeCount
                value: 1
                cooldown: PT5M
